application: ts
version: 11
runtime: python
api_version: 1
default_expiration: '3650d'

handlers:
- url: /media/admin_media
  static_dir: common/django_aep_export/admin_media/media

- url: /media
  static_dir: media

- url: /js
  static_dir: media/js

- url: /images
  static_dir: media/images

- url: /img
  static_dir: media/images

- url: /html
  static_dir: media/html

- url: /static
  static_dir: media/static
  
- url: /css
  static_dir: media/css
  
- url: /favicon.ico
  static_files: media/static/favicon.ico
  upload: media/static/favicon.ico

- url: /robots.txt
  static_files: media/static/robots.txt
  upload: media/static/robots.txt

- url: /xd_receiver.htm
  static_files: media/static/xd_receiver.htm
  upload: media/static/xd_receiver.htm
  
- url: /google917f051914d07e64.html
  static_files: media/static/xd_receiver.htm
  upload: media/static/xd_receiver.htm

- url: /load
  script: load/loader.py
  login: admin

- url: /feeds/calcportfolio
  script: common/appenginepatch/main.py
  login: admin
  
- url: /feeds/calchistory
  script: common/appenginepatch/main.py
  login: admin
    
- url: /.*
  script: common/appenginepatch/main.py
  
